#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# Idempotent MuJoCo-Warp bootstrap for a CUDA RunPod image with PyTorch installed.
set -Eeuo pipefail

PROJ="${PROJ:-/root/proj}"
VENV="${WARP_VENV:-$PROJ/.venv-warp}"
OUT="${CODESIGN_OUT:-$PROJ/out}"
REQ="$PROJ/requirements-warp.txt"

[[ -f "$REQ" ]] || { echo "missing dependency lock: $REQ" >&2; exit 2; }
mkdir -p "$OUT"

# Full verification includes the CPU-only Verilator/component regression. The
# GPU image therefore needs both CUDA PyTorch and the native co-simulation tools.
missing_native=0
for tool in cmake ninja verilator g++ ngspice yosys; do
  command -v "$tool" >/dev/null 2>&1 || missing_native=1
done
python3 -c 'import pathlib,sysconfig; assert (pathlib.Path(sysconfig.get_path("include")) / "Python.h").is_file()' \
  >/dev/null 2>&1 || missing_native=1
if ((missing_native)); then
  command -v apt-get >/dev/null 2>&1 || {
    echo "missing native verification tools and apt-get is unavailable" >&2
    exit 2
  }
  apt-get update
  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    build-essential cmake ninja-build python3-dev verilator ngspice yosys
fi

if [[ ! -x "$VENV/bin/python" ]]; then
  python3 -m venv --system-site-packages "$VENV"
fi

if command -v uv >/dev/null 2>&1; then
  uv pip install --python "$VENV/bin/python" -r "$REQ"
else
  "$VENV/bin/python" -m pip install --upgrade pip
  "$VENV/bin/python" -m pip install -r "$REQ"
fi

cat > "$OUT/warp_env.sh" <<EOF
# Generated by setup_warp_pod.sh; source before MuJoCo-Warp work.
export PATH="$VENV/bin:\$PATH"
export WARP_PY="$VENV/bin/python"
export MUJOCO_GL=""
export CODESIGN_OUT="$OUT"
export PYTHONHASHSEED=0
EOF

# shellcheck disable=SC1090
source "$OUT/warp_env.sh"
"$WARP_PY" - <<'PY'
import mujoco
import mujoco_warp
import torch
import warp

assert torch.cuda.is_available(), "CUDA PyTorch is required on the target pod"
print("SETUP_OK", "torch", torch.__version__, "warp", warp.__version__,
      "mujoco", mujoco.__version__, "gpu", torch.cuda.get_device_name(0))
PY

echo "source $OUT/warp_env.sh before running the launch gate"
