#!/bin/bash
# SPDX-License-Identifier: MIT
# One-shot, idempotent RunPod (4090/CUDA12) bootstrap for the MJX co-design stack.
# Bakes in every hard-won pod fix so we don't re-derive them each fresh (ephemeral) pod.
# Run ON the pod AFTER code is shipped to /root/proj:
#     /tmp/rp.sh 'bash /root/proj/sim/robot/setup_pod.sh'
# then source the env it writes before any run:
#     /tmp/rp.sh 'source /root/proj/out/env.sh && cd /root/proj/sim/robot && python3 -u combat_rank.py ...'
set -u
PROJ="${PROJ:-/root/proj}"
OUT="${CODESIGN_OUT:-$PROJ/out}"
REQ="$PROJ/requirements-gpu.txt"
VENV="$PROJ/venv"
mkdir -p "$OUT" "$OUT/.jax_cache"

echo "== [1/3] install into a clean venv (pinned jax0.6.2/brax0.14.1/mujoco3.9/numpy2.2.6) =="
# Modern pods (Ubuntu 24.04 / py3.12) are PEP-668 "externally managed" AND have debian-managed
# packages (e.g. blinker) with no RECORD file, so a system pip install both refuses and then
# fails to uninstall conflicts. A CLEAN venv sidesteps both — pip installs into it freely, and
# we don't need the pod's preinstalled torch (we use jax). env.sh puts the venv on PATH so plain
# `python3` (and subprocess `sys.executable`) resolve to it.
python3 -m venv "$VENV"
PIP="$VENV/bin/pip install -q"
$VENV/bin/python -m pip install -q --upgrade pip >/dev/null 2>&1
if [ -f "$REQ" ]; then
  $PIP -r "$REQ"
else  # fallback if requirements-gpu.txt wasn't shipped
  $PIP "jax[cuda12]==0.6.2" mujoco==3.9.0 mujoco-mjx==3.9.0 \
       brax==0.14.1 flax==0.10.7 optax==0.2.8 numpy==2.2.6
fi

echo "== [2/3] write $OUT/env.sh (the MANDATORY exports — source before every run) =="
cat > "$OUT/env.sh" <<EOF
# source me before any GPU run on this pod (generated by setup_pod.sh)
export PATH=$VENV/bin:\$PATH                  # the pinned venv (python3 -> $VENV/bin/python)
export MUJOCO_GL=""                          # pod osmesa/egl GL libs are BROKEN; empty imports clean (mj_step needs no GL)
export XLA_PYTHON_CLIENT_PREALLOCATE=false   # else a dead JAX proc holds ~17GB -> "cuSolver internal error"; one GPU => run stages SEQUENTIALLY
export CODESIGN_OUT=$OUT
export JAX_COMPILATION_CACHE_DIR=$OUT/.jax_cache  # skip ~150s recompiles of the heavy two-robot fight graph across runs
EOF

echo "== [3/3] smoke test (warp import warnings are HARMLESS — optional MJX backend we don't use) =="
# shellcheck disable=SC1090
source "$OUT/env.sh"
python3 -c "import jax,brax,mujoco,mujoco.mjx; print('devices:',jax.devices(),'| brax',brax.__version__)" \
  || { echo "SETUP_FAIL: stack did not import"; exit 1; }
echo "SETUP_OK: source $OUT/env.sh before runs"
