#!/usr/bin/env python3
"""Render rtl/gen/rtl_params.vh from sim/config/params.toml.

Single source of truth: the RTL never hardcodes a value that exists in the
config. Run by sim/scripts/build_bench.sh before cmake.
"""

from __future__ import annotations

import math
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import sim_params  # noqa: E402

PROJECT_ROOT = Path(__file__).resolve().parents[2]
OUT_PATH = PROJECT_ROOT / "rtl" / "gen" / "rtl_params.vh"
SINCOS_PATH = PROJECT_ROOT / "rtl" / "gen" / "sincos_init.vh"


def write_sincos_table(bits: int) -> None:
    """Quarter-wave sin table (Q15, [0, pi/2)) as Verilog array assignments,
    using the same rounding rule as foc_reference.sincos_table so the RTL and
    the Python reference agree bit-for-bit."""
    n = 1 << bits
    lines = [
        "// AUTO-GENERATED by sim/scripts/gen_rtl_params.py - DO NOT EDIT.",
        f"// Quarter-wave sin table, Q15, {n} entries (sincos_table_bits="
        f"{bits}).",
    ]
    for i in range(n):
        val = round(math.sin((i + 0.5) / n * (math.pi / 2.0)) * 32767)
        lines.append(f"tab[{i}] = 15'd{val};")
    SINCOS_PATH.parent.mkdir(parents=True, exist_ok=True)
    SINCOS_PATH.write_text("\n".join(lines) + "\n")
    print(f"wrote {SINCOS_PATH}")


def main() -> int:
    p = sim_params.load()

    clk_hz = p.value("rtl.clock_frequency")
    pwm_hz = p.value("pwm.frequency")
    dead_s = p.value("pwm.rtl_dead_time")

    pwm_half = int(round(clk_hz / (2.0 * pwm_hz)))  # up/down counter peak
    dead_cycles = int(math.ceil(dead_s * clk_hz))
    min_pulse_cycles = max(2, int(math.ceil(50e-9 * clk_hz)))  # DRV tON_MIN
    en_ready_cycles = int(math.ceil(
        (p.value("drv8301.en_gate_ready_time") + 2e-3) * clk_hz))
    quick_reset_cycles = max(4, int(round(4e-6 * clk_hz)))
    refresh_cycles = int(round(p.value("rtl.drv_refresh_period") * clk_hz))
    carrier_period_cycles = int(round(
        clk_hz / p.value("angle_sensor.pwm_carrier")))
    pole_pairs = int(p.value("motor.pole_pairs"))
    # speed [rad/s] = SPEED_NUM / sector_period_cycles (60 elec deg/sector).
    speed_num = int(round(clk_hz * 2.0 * math.pi / (6.0 * pole_pairs)))

    lines = [
        "// AUTO-GENERATED by sim/scripts/gen_rtl_params.py from",
        "// sim/config/params.toml - DO NOT EDIT.",
        "",
        f"`define CLK_HZ           {int(clk_hz)}",
        f"`define PWM_HALF_PERIOD  {pwm_half}",
        f"`define DEAD_CYCLES      {dead_cycles}",
        f"`define MIN_PULSE_CYCLES {min_pulse_cycles}",
        f"`define DRV_SPI_DIV      {int(p.value('rtl.drv_spi_divider'))}",
        f"`define ADC_SPI_DIV      {int(p.value('rtl.adc_spi_divider'))}",
        f"`define ADC_EMF_LEAD     {int(p.value('rtl.adc_emf_lead_cycles'))}",
        f"`define EN_READY_CYCLES  {en_ready_cycles}",
        f"`define QUICK_RESET_CYC  {quick_reset_cycles}",
        f"`define DRV_REFRESH_CYC  {refresh_cycles}",
        f"`define POLE_PAIRS       {int(p.value('motor.pole_pairs'))}",
        f"`define OC_ADJ_CODE      {int(p.value('rtl.oc_adj_code'))}",
        f"`define AMP_GAIN_CODE    {int(p.value('rtl.amp_gain_code'))}",
        f"`define SPEED_PI_KP      {int(p.value('rtl.speed_pi_kp'))}",
        f"`define SPEED_PI_KI_SHIFT {int(p.value('rtl.speed_pi_ki_shift'))}",
        f"`define ANGLE_CARRIER_CYC {carrier_period_cycles}",
        f"`define SPEED_NUM        {speed_num}",
        f"`define DUTY_DOWN_SLEW   {int(p.value('rtl.duty_down_slew'))}",
        f"`define UART_DIV         {int(round(clk_hz / p.value('rtl.uart_baud')))}",
        # Edge-case policy constants (edge-case-scenarios.md).
        f"`define SECTOR_HYST      {int(p.value('rtl.sector_hysteresis'))}",
        f"`define EMF_SKIP_MARGIN  {int(p.value('rtl.emf_skip_duty_margin'))}",
        f"`define DC_CAL_TOL       {int(p.value('rtl.dc_cal_offset_tol'))}",
        f"`define DRV_DEAD_N       {int(p.value('rtl.drv_dead_threshold'))}",
        f"`define LOCKOUT_N        {int(p.value('rtl.fault_lockout_threshold'))}",
        f"`define STALL_CYC        {int(round(p.value('rtl.stall_timeout') * clk_hz))}",
        f"`define UART_TIMEOUT_CYC {int(round(p.value('rtl.uart_byte_timeout') * clk_hz))}",
        f"`define ADC_STUCK_N      {int(p.value('rtl.adc_stuck_threshold'))}",
        f"`define HEALTHY_RUN_CYC  {int(round(0.1 * clk_hz))}",
        "",
        "// Field-oriented control (foc-checklist.md; foc-fixed-point.md).",
        f"`define SINCOS_TABLE_BITS {int(p.value('foc.sincos_table_bits'))}",
        f"`define CUR_PI_KP        {int(p.value('foc.cur_pi_kp'))}",
        f"`define CUR_PI_KI_SHIFT  {int(p.value('foc.cur_pi_ki_shift'))}",
        f"`define ID_TARGET        {int(p.value('foc.id_target'))}",
        # Voltage-circle radius in duty units: the SVPWM inscribed circle has
        # radius PWM_HALF_PERIOD in the (vd,vq) scaling; v_circle_limit leaves
        # headroom for dead time and min-pulse.
        f"`define V_CIRCLE_LIMIT   {int(round(pwm_half * p.value('foc.v_circle_limit')))}",
        # Per-axis raw PI output clamp (keeps vd^2+vq^2 within 32-bit before
        # the circle limiter; the limiter then caps the vector to V_CIRCLE).
        f"`define V_RAW_MAX        {4 * pwm_half}",
        f"`define ANGLE_EXTRAP_EN  {int(p.value('foc.angle_extrap_enable'))}",
        f"`define SPEED_IQ_KP      {int(p.value('foc.speed_kp'))}",
        f"`define SPEED_IQ_KISH    {int(p.value('foc.speed_ki_shift'))}",
        f"`define IQ_MAX           {int(p.value('foc.iq_max'))}",
        # Angle-latency extrapolation (stage 7, Q22): the dq angle is advanced
        # by omega_e * t_latency to undo the AS5600 frame+filter lag. In elec12
        # counts: d_elec12 = speed_radps * EXTRAP_NUM >> EXTRAP_SH, with
        # EXTRAP_NUM = pole_pairs * latency * 4096/(2pi) * 2^EXTRAP_SH.
        "`define EXTRAP_SH        8",
        f"`define EXTRAP_NUM       {int(round(pole_pairs * p.value('foc.angle_latency_s') * 4096.0 / (2.0 * math.pi) * 256))}",
        "",
    ]
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text("\n".join(lines))
    print(f"wrote {OUT_PATH}")
    write_sincos_table(int(p.value("foc.sincos_table_bits")))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
