#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Render formal/proof_report.md from manifest.toml + work/results.json.

The proof report is the project's "what we have proven, and under what
assumptions" artifact. It leads with the status breakdown (the formal analogue
of the assumption banner), then per-check detail with the assumptions each
proof relies on and the non-vacuity cover status, then two completeness views.
"""

from __future__ import annotations

import json
import tomllib
from pathlib import Path

FORMAL_DIR = Path(__file__).resolve().parent
MANIFEST = FORMAL_DIR / "manifest.toml"
RESULTS = FORMAL_DIR / "work" / "results.json"
REPORT = FORMAL_DIR / "proof_report.md"

STATUS_ICON = {"PROVEN": "✅ PROVEN", "FAILED": "❌ FAILED",
               "INCOMPLETE": "⚠️ INCOMPLETE (vacuous)",
               "DOCUMENTED": "📄 DOCUMENTED (not machine-proven)"}


def status_label(s):
    if s.startswith("BOUNDED"):
        return f"🔶 {s}"
    return STATUS_ICON.get(s, s)


def main():
    checks = tomllib.loads(MANIFEST.read_text())["check"]
    results = {r["id"]: r for r in json.loads(RESULTS.read_text())}

    lines = []
    a = lines.append
    a("# Formal Proof Report")
    a("")
    a("Generated by `formal/gen_proof_report.py` from `formal/manifest.toml` +")
    a("`formal/work/results.json`. Regenerate: `python3 formal/run_formal.py "
      "&& python3 formal/gen_proof_report.py`. See "
      "[`notes/formal-checklist.md`](../notes/formal-checklist.md).")
    a("")
    a("**This is verification, not validation.** Each result is a property of")
    a("the RTL under the stated assumptions - it says nothing about whether the")
    a("RTL matches real silicon or the real motor (that needs hardware). A")
    a("**PROVEN** result is an *unbounded* proof (k-induction/PDR converged);")
    a("**BOUNDED(N)** means no counterexample within N cycles, not a proof;")
    a("**INCOMPLETE** means the proof passed but a non-vacuity cover was")
    a("unreachable (the proof may be vacuous).")
    a("")

    # ---- Status banner -----------------------------------------------------
    counts = {}
    for r in results.values():
        key = r["status"].split("(")[0]
        counts[key] = counts.get(key, 0) + 1
    a("## Status")
    a("")
    a("| Status | Count |")
    a("| --- | --- |")
    for k in ("PROVEN", "BOUNDED", "DOCUMENTED", "INCOMPLETE", "FAILED"):
        if counts.get(k):
            a(f"| {status_label(k)} | {counts[k]} |")
    a("")

    # ---- Per-check detail --------------------------------------------------
    a("## Proven properties")
    a("")
    for c in checks:
        r = results.get(c["id"])
        if not r:
            a(f"### `{c['id']}` ({c['module']}) — ⚪ NO RESULT")
            a("")
            continue
        scope = c.get("param_scope", "config")
        scope_txt = ("motorloop config" if scope == "config"
                     else f"parameter envelope: {c.get('envelope', '?')}")
        a(f"### `{c['id']}` — {c['module']}")
        a("")
        a(f"**{status_label(r['status'])}** · {c['category']} · "
          f"{r['method']} ({r['engine']}, depth {r['depth']}) · "
          f"scope: {scope_txt}")
        if r.get("covers"):
            a(f" · non-vacuity covers: "
              f"{'✅ reachable' if r['covers'] == 'REACHED' else '❌ ' + r['covers']}")
        a("")
        a("Proves:")
        for p in c.get("properties", []):
            a(f"- {p}")
        a("")
        a("Under assumptions:")
        for asm in c.get("assumptions", []):
            a(f"- {asm}")
        a("")
        if c.get("cover_props"):
            a("Non-vacuity (the interesting states are reachable):")
            for cp in c["cover_props"]:
                a(f"- {cp}")
            a("")
        a(f"_{c.get('justification', '')}_")
        a("")

    # ---- Completeness views ------------------------------------------------
    a("## Completeness")
    a("")
    a("**Coverage of properties** — which modules carry formal proofs "
      "(the \"is the proof surface complete?\" question):")
    a("")
    modules = sorted({c["module"] for c in checks})
    for m in modules:
        ids = [c["id"] for c in checks if c["module"] == m]
        a(f"- `{m}`: {', '.join(ids)}")
    a("")
    a("**Coverage of reachability / non-vacuity** — which safety proofs have "
      "passing covers (the \"are these proofs vacuous?\" guard):")
    a("")
    for c in checks:
        if c["category"] != "safety":
            continue
        r = results.get(c["id"], {})
        cov = r.get("covers") or "no covers declared"
        mark = "✅" if cov == "REACHED" else "⚠️"
        a(f"- {mark} `{c['id']}`: {cov}")
    a("")

    while lines and lines[-1] == "":
        lines.pop()
    REPORT.write_text("\n".join(lines) + "\n")
    print(f"wrote {REPORT}")


if __name__ == "__main__":
    raise SystemExit(main())
