#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Render the compact cross-domain status evidence page.

Formal results come from formal/work/results.json when a proof run is present.
On clean documentation/release jobs that intentionally do not rerun formal, the
last generated formal/proof_report.md is the fallback evidence. ECP5 timing comes
only from synth/synth_report.md.
"""

from __future__ import annotations

import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
RESULTS = ROOT / "formal/work/results.json"
PROOF_REPORT = ROOT / "formal/proof_report.md"
SYNTH = ROOT / "synth/synth_report.md"
OUT = ROOT / "notes/status-matrix-generated.md"


def formal_summary() -> tuple[int, int, int, int, str]:
    if RESULTS.exists():
        results = json.loads(RESULTS.read_text())
        proven = sum(r.get("status") == "PROVEN" for r in results)
        documented = sum(r.get("status") == "DOCUMENTED" for r in results)
        other = len(results) - proven - documented
        envelope = sum(
            r.get("status") == "PROVEN" and r.get("param_scope") == "envelope"
            for r in results
        )
        return proven, documented, other, envelope, "formal/work/results.json"

    if PROOF_REPORT.exists():
        text = PROOF_REPORT.read_text()
        proven_match = re.search(r"\| ✅ PROVEN \| (\d+) \|", text)
        documented_match = re.search(r"\| 📄 DOCUMENTED \(not machine-proven\) \| (\d+) \|", text)
        incomplete_counts = [
            int(value)
            for value in re.findall(
                r"\| (?:🔶 BOUNDED|⚠️ INCOMPLETE|❌ FAILED)[^|]*\| (\d+) \|",
                text,
            )
        ]
        envelope = len(re.findall(r"scope: parameter envelope:", text))
        return (
            int(proven_match.group(1)) if proven_match else 0,
            int(documented_match.group(1)) if documented_match else 0,
            sum(incomplete_counts),
            envelope,
            "formal/proof_report.md (last rendered proof run)",
        )

    return 0, 0, 0, 0, "no formal evidence found"


def main() -> None:
    proven, documented, other, envelope, formal_source = formal_summary()
    lines = [
        "<!-- SPDX-License-Identifier: MIT -->",
        "<!-- GENERATED by notes/gen_status_matrix.py - do not edit. -->",
        "# Status evidence (generated)",
        "",
        "This compact page prevents volatile proof counts and ECP5 timing from being",
        "copied through hand-authored guides. Follow the source reports for detail.",
        "",
        "## Formal",
        "",
        f"- **{proven} PROVEN** ({envelope} parameter-generic / envelope)",
        f"- **{documented} DOCUMENTED**, **{other} other**",
        f"- Source: `{formal_source}`; per-property detail: `formal/proof_report.md`",
        "",
    ]

    if SYNTH.exists():
        text = SYNTH.read_text()
        match = re.search(r"Post-route Fmax estimate:\s*\*\*([\d.]+ MHz)\*\*", text)
        timing = match.group(1) if match else "n/a"
        lines += [
            "## Synthesis (open ECP5 place-and-route)",
            "",
            f"- Post-route Fmax: **{timing}** (configured target: 25 MHz)",
            "- Fit and utilization source: `synth/synth_report.md`",
        ]
    else:
        lines += ["## Synthesis", "", "_No synthesis report is present._"]

    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
