#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Regenerate the live facts of the status matrix from machine outputs
(trusted-library-checklist stage 3.3): the formal proof column from
formal/work/results.json and the synth fit from synth/synth_report.md.

Writes notes/status-matrix-generated.md (the CI artifact). The hand-authored
notes/status-matrix.md carries the per-module narrative; this carries the live
totals so a reviewer sees the current proven/fit state on every run.

  python3 notes/gen_status_matrix.py
"""

from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RESULTS = ROOT / "formal" / "work" / "results.json"
SYNTH = ROOT / "synth" / "synth_report.md"
OUT = ROOT / "notes" / "status-matrix-generated.md"


def main():
    # REUSE-IgnoreStart
    lines = ["<!-- SPDX-License-Identifier: MIT -->",
             "<!-- GENERATED by notes/gen_status_matrix.py - do not edit. -->",
             "# Status matrix (generated)", ""]
    # REUSE-IgnoreEnd

    if RESULTS.exists():
        results = json.loads(RESULTS.read_text())
        proven = [r for r in results if r.get("status") == "PROVEN"]
        documented = [r for r in results if r.get("status") == "DOCUMENTED"]
        other = [r for r in results
                 if r.get("status") not in ("PROVEN", "DOCUMENTED")]
        envelope = [r for r in proven if r.get("param_scope") == "envelope"]
        lines += [f"**Formal:** {len(proven)} PROVEN "
                  f"({len(envelope)} parameter-generic / envelope), "
                  f"{len(documented)} DOCUMENTED, {len(other)} other.", ""]
        lines.append("| Proof | Status | Covers | Scope |")
        lines.append("| --- | --- | --- | --- |")
        for r in results:
            lines.append(f"| `{r['id']}` | {r.get('status','?')} | "
                         f"{r.get('covers','-')} | {r.get('param_scope','-')} |")
        if other:
            lines += ["", f"**WARNING: {len(other)} proof(s) not PROVEN/"
                      f"DOCUMENTED — the gate should fail.**"]
    else:
        lines.append("_(no formal results.json — run formal/run_formal.py)_")

    lines.append("")
    if SYNTH.exists():
        txt = SYNTH.read_text()
        m = re.search(r"Fmax estimate:\s*\*\*([\d.]+ MHz)\*\*", txt)
        fit = "see synth/synth_report.md"
        lines += ["## Synthesis (ECP5)",
                  f"- Post-route Fmax: **{m.group(1) if m else 'n/a'}** "
                  f"(target 25 MHz)", f"- Fit detail: {fit}"]
    else:
        lines += ["## Synthesis", "_(no synth report — run synth/run_synth.py)_"]

    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
