#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Check documentation lifecycle, navigation, local links, and live evidence.

The lifecycle map is docs-lifecycle.toml. The default mode is read-only and
fails when notes/document-catalog.md is stale. Use --write-catalog after adding
or reclassifying documentation, then run the default check again.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
import tomllib
from dataclasses import dataclass
from pathlib import Path, PurePosixPath
from urllib.parse import unquote


ROOT = Path(__file__).resolve().parent.parent
CONFIG = ROOT / "docs-lifecycle.toml"
CATALOG = ROOT / "notes" / "document-catalog.md"
VALID_STATUSES = {"current", "active", "reference", "generated", "historical", "retired"}
LINK_RE = re.compile(r"!?\[[^\]]*\]\(([^)]+)\)")
HEADER_RE = re.compile(r">\s*\*\*Document status:\*\*\s*([A-Za-z]+)", re.IGNORECASE)
FENCE_RE = re.compile(r"^\s*(```|~~~)")


@dataclass(frozen=True)
class Meta:
    path: str
    status: str
    kind: str
    audience: str
    canonical_for: str = "—"
    header_required: bool = False


def inventory() -> list[str]:
    proc = subprocess.run(
        ["git", "ls-files", "--cached", "--others", "--exclude-standard"],
        cwd=ROOT,
        check=True,
        text=True,
        stdout=subprocess.PIPE,
    )
    return sorted(
        p for p in proc.stdout.splitlines()
        if p.endswith(".md") and not p.startswith(("site/", "site-src/"))
    )


def load_config() -> tuple[dict, list[dict], dict[str, dict]]:
    data = tomllib.loads(CONFIG.read_text())
    if data.get("schema_version") != 1:
        raise ValueError("docs-lifecycle.toml schema_version must be 1")
    rules = data.get("rules", [])
    overrides = {entry["path"]: entry for entry in data.get("overrides", [])}
    return data, rules, overrides


def matches(path: str, pattern: str) -> bool:
    return PurePosixPath(path).match(pattern)


def classify(path: str, rules: list[dict], overrides: dict[str, dict]) -> Meta | None:
    resolved: dict[str, object] = {}
    for rule in rules:
        if matches(path, rule["glob"]):
            resolved.update({k: v for k, v in rule.items() if k != "glob"})
    if path in overrides:
        resolved.update({k: v for k, v in overrides[path].items() if k != "path"})
    if not resolved:
        return None
    return Meta(
        path=path,
        status=str(resolved.get("status", "")),
        kind=str(resolved.get("kind", "")),
        audience=str(resolved.get("audience", "")),
        canonical_for=str(resolved.get("canonical_for", "—")),
        header_required=bool(resolved.get("header_required", False)),
    )


def title_and_summary(path: Path) -> tuple[str, str]:
    text = path.read_text(errors="replace")
    title_match = re.search(r"^#\s+(.+)$", text, re.MULTILINE)
    title = title_match.group(1).strip() if title_match else path.stem

    paragraphs: list[str] = []
    current: list[str] = []
    in_fence = False
    for line in text.splitlines():
        if FENCE_RE.match(line):
            in_fence = not in_fence
            continue
        if line.lstrip().startswith(("[![", "![")):
            continue
        if in_fence or line.startswith(("#", "<!--", "> **Document status:**", "|", "- ", "* ")):
            if current:
                paragraphs.append(" ".join(current))
                current = []
            continue
        if not line.strip():
            if current:
                paragraphs.append(" ".join(current))
                current = []
            continue
        current.append(line.strip())
    if current:
        paragraphs.append(" ".join(current))
    summary = next((p for p in paragraphs if len(p) > 20), title)
    summary = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", summary)
    summary = summary.replace("`", "").replace("|", "\\|")
    if len(summary) > 180:
        summary = summary[:177].rsplit(" ", 1)[0] + "…"
    return title.replace("|", "\\|"), summary


def render_catalog(metadata: dict[str, Meta], reviewed: str) -> str:
    order = {name: i for i, name in enumerate(
        ["current", "active", "reference", "generated", "historical", "retired"]
    )}
    lines = [
        "<!-- SPDX-License-Identifier: MIT -->",
        "<!-- GENERATED by scripts/check_docs.py --write-catalog; do not edit. -->",
        "# Documentation catalog",
        "",
        f"> **Document status:** Generated · **Lifecycle map reviewed:** {reviewed} · "
        "**Canonical for:** Complete Markdown inventory",
        "",
        "Use [`README.md`](README.md) for curated navigation. This table is the",
        "exhaustive inventory and makes every document's resolved lifecycle visible.",
        "",
    ]
    grouped: dict[str, list[Meta]] = {status: [] for status in order}
    for meta in metadata.values():
        grouped[meta.status].append(meta)
    for status in sorted(grouped, key=order.get):
        entries = sorted(grouped[status], key=lambda m: m.path)
        if not entries:
            continue
        lines += [f"## {status.title()}", "", "| Document | Kind | Audience | Description |", "| --- | --- | --- | --- |"]
        for meta in entries:
            title, summary = title_and_summary(ROOT / meta.path)
            rel = Path(meta.path).relative_to("notes") if meta.path.startswith("notes/") else Path("..") / meta.path
            link = rel.as_posix()
            lines.append(f"| [{title}]({link}) | {meta.kind} | {meta.audience} | {summary} |")
        lines.append("")
    return "\n".join(lines)


def strip_fenced_code(text: str) -> str:
    kept: list[str] = []
    in_fence = False
    marker = ""
    for line in text.splitlines():
        m = FENCE_RE.match(line)
        if m:
            token = m.group(1)
            if not in_fence:
                in_fence, marker = True, token
            elif token == marker:
                in_fence = False
            continue
        if not in_fence:
            kept.append(line)
    return "\n".join(kept)


def local_targets(source: Path) -> list[tuple[str, Path]]:
    text = strip_fenced_code(source.read_text(errors="replace"))
    found: list[tuple[str, Path]] = []
    for raw in LINK_RE.findall(text):
        raw = raw.strip()
        if raw.startswith("<") and raw.endswith(">"):
            raw = raw[1:-1]
        # Remove an optional Markdown title after the destination.
        raw = re.split(r"\s+[\"']", raw, maxsplit=1)[0]
        if not raw or raw.startswith(("http://", "https://", "mailto:", "#", "data:")):
            continue
        destination = unquote(raw.split("#", 1)[0])
        if not destination or any(ch in destination for ch in "*{}"):
            continue
        target = (source.parent / destination).resolve()
        found.append((raw, target))
    return found


def relative_to_root(path: Path) -> str | None:
    try:
        return path.relative_to(ROOT).as_posix()
    except ValueError:
        return None


def evidence_checks(errors: list[str]) -> None:
    synth = (ROOT / "synth/synth_report.md").read_text()
    generated = (ROOT / "notes/status-matrix-generated.md").read_text()
    synth_match = re.search(r"Post-route Fmax estimate:\s*\*\*([\d.]+ MHz)\*\*", synth)
    matrix_match = re.search(r"Post-route Fmax:\s*\*\*([\d.]+ MHz)\*\*", generated)
    if not synth_match or not matrix_match or synth_match.group(1) != matrix_match.group(1):
        errors.append("status-matrix-generated.md does not match synth/synth_report.md Fmax")

    proof = (ROOT / "formal/proof_report.md").read_text()
    proof_proven = re.search(r"\| ✅ PROVEN \| (\d+) \|", proof)
    matrix_proven = re.search(r"\*\*(\d+) PROVEN\*\*", generated)
    if not proof_proven or not matrix_proven or proof_proven.group(1) != matrix_proven.group(1):
        errors.append("status-matrix-generated.md does not match formal/proof_report.md count")

    legacy = (ROOT / "notes/status-matrix.md").read_text()
    if re.search(r"Fmax\s*[≈~]?\s*3\.3 MHz|pipeline needed", legacy, re.IGNORECASE):
        errors.append("notes/status-matrix.md still contains the superseded 3.3 MHz timing claim")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write-catalog", action="store_true", help="regenerate notes/document-catalog.md")
    args = parser.parse_args()

    config, rules, overrides = load_config()
    paths = inventory()
    metadata: dict[str, Meta] = {}
    errors: list[str] = []
    for path in paths:
        meta = classify(path, rules, overrides)
        if meta is None:
            errors.append(f"unclassified Markdown: {path}")
            continue
        if meta.status not in VALID_STATUSES:
            errors.append(f"invalid lifecycle status {meta.status!r}: {path}")
        if not meta.kind or not meta.audience:
            errors.append(f"incomplete lifecycle metadata: {path}")
        metadata[path] = meta

    for meta in metadata.values():
        source = ROOT / meta.path
        text = source.read_text(errors="replace")
        if meta.header_required:
            match = HEADER_RE.search("\n".join(text.splitlines()[:15]))
            if not match:
                errors.append(f"required document-status header missing: {meta.path}")
            elif match.group(1).lower() != meta.status:
                errors.append(
                    f"header status {match.group(1)!r} disagrees with lifecycle {meta.status!r}: {meta.path}"
                )

        if meta.status in {"current", "active", "reference", "generated"}:
            for raw, target in local_targets(source):
                rel = relative_to_root(target)
                if rel is None:
                    errors.append(f"local link escapes repository in {meta.path}: {raw}")
                    continue
                if not target.exists():
                    errors.append(f"broken local link in {meta.path}: {raw}")
                    continue
                target_meta = metadata.get(rel)
                if (
                    meta.status in {"current", "active"}
                    and target_meta is not None
                    and target_meta.status == "retired"
                    and meta.path != "notes/archive/README.md"
                ):
                    errors.append(f"current document links directly to retired guidance: {meta.path} -> {rel}")

    required_links = {
        "README.md": ["notes/README.md", "notes/current-status.md", "notes/system-architecture.md", "notes/reader-paths.md"],
        "notes/README.md": ["getting-started.md", "current-status.md", "system-architecture.md", "reader-paths.md", "archive/README.md"],
    }
    for source, needles in required_links.items():
        text = (ROOT / source).read_text()
        for needle in needles:
            if needle not in text:
                errors.append(f"required navigation link {needle!r} missing from {source}")

    if all((ROOT / p).exists() for p in ("synth/synth_report.md", "formal/proof_report.md", "notes/status-matrix-generated.md", "notes/status-matrix.md")):
        evidence_checks(errors)

    expected_catalog = render_catalog(metadata, str(config["last_reviewed"]))
    if args.write_catalog:
        CATALOG.write_text(expected_catalog)
        print(f"wrote {CATALOG.relative_to(ROOT)} ({len(metadata)} documents)")
    elif not CATALOG.exists():
        errors.append("notes/document-catalog.md is missing; run scripts/check_docs.py --write-catalog")
    elif CATALOG.read_text() != expected_catalog:
        errors.append("notes/document-catalog.md is stale; run scripts/check_docs.py --write-catalog")

    if errors:
        for error in errors:
            print(f"docs: ERROR: {error}", file=sys.stderr)
        print(f"docs: {len(errors)} error(s)", file=sys.stderr)
        return 1
    print(f"docs: OK ({len(metadata)} Markdown files classified and checked)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
