#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Generate IEEE 1685-2014 (IP-XACT) component XML for the bus-wrapped blocks
(robotics-ip-checklist stage 9). The register map below is the single source -
it matches rtl/bus/axil_regfile.v; an EDA tool / SoC integrator ingests this to
wire the controller's registers into a memory map.

  python3 scripts/gen_ipxact.py   ->  ip-xact/motorloop.axil_regfile.xml
"""

from __future__ import annotations

import xml.sax.saxutils as sx
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "ip-xact"
NS = "http://www.accellera.org/XMLSchema/IPXACT/1685-2014"

# (offset, name, [(field, bitOffset, bitWidth)], access, description)
RW, RO = "read-write", "read-only"
REGS = [
    (0x00, "mode", [("mode", 0, 2)], RW, "control mode (0 idle,1 OL,2 six-step,3 FOC)"),
    (0x04, "duty", [("duty", 0, 16)], RW, "open-loop duty compare"),
    (0x08, "target_speed", [("target_speed", 0, 16)], RW, "speed target (rad/s)"),
    (0x0C, "align", [("align", 0, 12)], RW, "electrical-angle alignment offset"),
    (0x10, "ol_freq_word_hi", [("v", 0, 16)], RW, "open-loop freq word [31:16]"),
    (0x14, "ol_freq_word_lo", [("v", 0, 16)], RW, "open-loop freq word [15:0]"),
    (0x18, "ol_ramp_inc_hi", [("v", 0, 16)], RW, "open-loop ramp increment [31:16]"),
    (0x1C, "ol_ramp_inc_lo", [("v", 0, 16)], RW, "open-loop ramp increment [15:0]"),
    (0x20, "control", [("use_axi", 0, 1)], RW, "bit0: AXI overrides direct ctrl_*"),
    (0x40, "speed", [("speed", 0, 16)], RO, "measured speed (rad/s)"),
    (0x44, "fault_counts", [("mismatch", 0, 8), ("fault", 8, 8)], RO, "fault/mismatch counts"),
    (0x48, "angle", [("angle", 0, 12)], RO, "rotor angle (12-bit)"),
    (0x4C, "noctw_count", [("noctw", 0, 16)], RO, "nOCTW event count"),
    (0x50, "status", [("sector", 0, 3), ("configured", 3, 1)], RO, "configured + sector"),
    (0x54, "flags", [("flags", 0, 8)], RO, "stall/lockout/dead/reverse flags"),
]


def _field(name, off, width, access):
    return (f"        <ipxact:field>\n"
            f"          <ipxact:name>{name}</ipxact:name>\n"
            f"          <ipxact:bitOffset>{off}</ipxact:bitOffset>\n"
            f"          <ipxact:bitWidth>{width}</ipxact:bitWidth>\n"
            f"          <ipxact:access>{access}</ipxact:access>\n"
            f"        </ipxact:field>")


def _register(off, name, fields, access, desc):
    fs = "\n".join(_field(fn, fo, fw, access) for fn, fo, fw in fields)
    return (f"      <ipxact:register>\n"
            f"        <ipxact:name>{name}</ipxact:name>\n"
            f"        <ipxact:description>{sx.escape(desc)}</ipxact:description>\n"
            f"        <ipxact:addressOffset>{hex(off)}</ipxact:addressOffset>\n"
            f"        <ipxact:size>32</ipxact:size>\n"
            f"{fs}\n"
            f"      </ipxact:register>")


def _memory_map():
    regs = "\n".join(_register(*r) for r in REGS)
    return f"""  <ipxact:memoryMaps>
    <ipxact:memoryMap>
      <ipxact:name>regs</ipxact:name>
      <ipxact:addressBlock>
        <ipxact:name>control_telemetry</ipxact:name>
        <ipxact:baseAddress>0x0</ipxact:baseAddress>
        <ipxact:range>0x100</ipxact:range>
        <ipxact:width>32</ipxact:width>
        <ipxact:usage>register</ipxact:usage>
{regs}
      </ipxact:addressBlock>
    </ipxact:memoryMap>
  </ipxact:memoryMaps>
"""


# (module, port, busType VLNV attrs, interface-mode XML). The register-mapped
# slaves share the ONE register map (_memory_map / REGS); the stream master
# carries no memory map - an honest IP-XACT describes its interface only.
SLAVE = '<ipxact:slave><ipxact:memoryMapRef memoryMapRef="regs"/></ipxact:slave>'
BLOCKS = [
    ("axil_regfile", "s_axi",
     'vendor="amba.com" library="AMBA4" name="AXI4Lite" version="r0p0_0"',
     SLAVE, True),
    ("wb_regfile", "s_wb",
     'vendor="opencores.org" library="bus" name="Wishbone" version="b4"',
     SLAVE, True),
    ("axis_sampler", "m_axis",
     'vendor="amba.com" library="AMBA4" name="AXI4Stream" version="r0p0_0"',
     "<ipxact:master/>", False),
]


def component(module, port, bustype, mode, has_regmap):
    mmap = _memory_map() if has_regmap else ""
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<!-- SPDX-License-Identifier: MIT -->
<!-- GENERATED by scripts/gen_ipxact.py - register map is the single source. -->
<ipxact:component xmlns:ipxact="{NS}">
  <ipxact:vendor>liminalnook</ipxact:vendor>
  <ipxact:library>motorloop</ipxact:library>
  <ipxact:name>{module}</ipxact:name>
  <ipxact:version>0.1.0</ipxact:version>
  <ipxact:busInterfaces>
    <ipxact:busInterface>
      <ipxact:name>{port}</ipxact:name>
      <ipxact:busType {bustype}/>
      {mode}
    </ipxact:busInterface>
  </ipxact:busInterfaces>
{mmap}  <ipxact:model>
    <ipxact:views>
      <ipxact:view>
        <ipxact:name>rtl</ipxact:name>
        <ipxact:componentInstantiationRef>verilog</ipxact:componentInstantiationRef>
      </ipxact:view>
    </ipxact:views>
    <ipxact:instantiations>
      <ipxact:componentInstantiation>
        <ipxact:name>verilog</ipxact:name>
        <ipxact:language>verilog</ipxact:language>
        <ipxact:moduleName>{module}</ipxact:moduleName>
      </ipxact:componentInstantiation>
    </ipxact:instantiations>
  </ipxact:model>
</ipxact:component>
"""


def main():
    OUT.mkdir(exist_ok=True)
    for module, port, bustype, mode, has_regmap in BLOCKS:
        path = OUT / f"motorloop.{module}.xml"
        path.write_text(component(module, port, bustype, mode, has_regmap))
        print(f"wrote {path}")
    print(f"{len(BLOCKS)} components; register map ({len(REGS)} regs) is one source")


if __name__ == "__main__":
    main()
