#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Per-module standalone Fmax (FOC Fmax-optimization checklist, task 0).

Wraps one module in a registered ring (every data input fed from a flop, every
output captured in a flop) so nextpnr times the module's internal reg->reg paths
instead of unconstrained I/O, then runs yosys synth_ecp5 + nextpnr-ecp5 and
reports the post-route Fmax. This is the instrument used to find/confirm the
critical block at each optimization step (read work/fmax_<m>.log for the path).

  source ~/oss-cad-suite/environment
  python3 synth/fmax_module.py speed_iq_pi foc_core circle_limit_seq

Module sources come from <module>.core (one source, like asic_smoke.py). Module
parameters take their RTL defaults (the as-built config).
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
WORK = ROOT / "synth" / "work"
DEVICE, PACKAGE = "--85k", "CABGA381"


def core_sources(block: str) -> list[str]:
    text = (ROOT / f"{block}.core").read_text()
    rtl = re.findall(r"^\s*-\s+(rtl/\S+\.v)\b", text, re.M)
    seen: set[str] = set()
    return [f for f in rtl if not (f in seen or seen.add(f))]


def ports(module_file: Path, module: str):
    """Parse the port list of `module` -> [(dir, signed, msb_expr_or_None, name)]."""
    src = module_file.read_text()
    i = src.index(f"module {module}")
    # skip an optional #( ... ) parameter block, then take the ( ... ) port group
    j = src.index("(", i)
    if src[i:j].count("#"):                       # params present: find their ')'
        depth = 0
        k = src.index("#", i)
        k = src.index("(", k)
        while True:
            if src[k] == "(":
                depth += 1
            elif src[k] == ")":
                depth -= 1
                if depth == 0:
                    break
            k += 1
        j = src.index("(", k + 1)
    depth, k = 0, j
    while True:
        if src[k] == "(":
            depth += 1
        elif src[k] == ")":
            depth -= 1
            if depth == 0:
                break
        k += 1
    body = src[j + 1:k]
    out = []
    for m in re.finditer(
            r"\b(input|output)\s+(?:wire|reg)\s+(signed\s+)?"
            r"(?:\[([^\]]+)\]\s+)?(\w+)", body):
        out.append((m.group(1), bool(m.group(2)), m.group(3), m.group(4)))
    return out


def ring(module_file: Path, module: str) -> str:
    decls, conns, in_regs, out_regs, top_ports = [], [], [], [], []
    for d, sgn, msb, name in ports(module_file, module):
        if name in ("clk", "rst_n"):
            top_ports.append(f"input {name}")
            conns.append(f".{name}({name})")
            continue
        w = f"[{msb}] " if msb else ""
        s = "signed " if sgn else ""
        if d == "input":
            top_ports.append(f"input {s}{w}p_{name}")
            decls.append(f"  reg {s}{w}r_{name};")
            in_regs.append(f"    r_{name} <= p_{name};")
            conns.append(f".{name}(r_{name})")
        else:
            top_ports.append(f"output {s}{w}p_{name}")
            decls.append(f"  wire {s}{w}w_{name};")
            decls.append(f"  reg {s}{w}r_{name};")
            out_regs.append(f"    r_{name} <= w_{name};")
            decls.append(f"  assign p_{name} = r_{name};")
            conns.append(f".{name}(w_{name})")
    # REUSE-IgnoreStart (SPDX tag below is emitted INTO the generated ring file)
    return (
        "// SPDX-License-Identifier: MIT\n"
        f"// GENERATED by synth/fmax_module.py - registered ring around {module}.\n"
        f"module ring_{module} (\n  " + ",\n  ".join(top_ports) + "\n);\n"
        + "\n".join(decls) + "\n"
        "  always @(posedge clk) begin\n" + "\n".join(in_regs + out_regs) + "\n  end\n"
        f"  {module} dut (\n    " + ",\n    ".join(conns) + "\n  );\nendmodule\n")
    # REUSE-IgnoreEnd


def measure(module: str) -> dict:
    files = core_sources(module)
    mfile = ROOT / f"rtl/{module}.v"
    if not mfile.exists():
        mfile = ROOT / f"rtl/bus/{module}.v"
    ringfile = WORK / f"ring_{module}.v"
    WORK.mkdir(parents=True, exist_ok=True)
    ringfile.write_text(ring(mfile, module))
    reads = "\n".join(f"read_verilog -I rtl -I rtl/gen {f}" for f in files)
    json_out = WORK / f"fmax_{module}.json"
    ys = f"""
{reads}
read_verilog -I rtl -I rtl/gen {ringfile}
synth_ecp5 -top ring_{module} -json {json_out}
"""
    log = WORK / f"fmax_{module}.log"
    with log.open("w") as f:
        ry = subprocess.run(["yosys", "-p", ys], cwd=ROOT, stdout=f,
                            stderr=subprocess.STDOUT)
        if ry.returncode != 0 or not json_out.exists():
            return {"module": module, "fmax": None, "err": "yosys"}
        rp = subprocess.run(
            ["nextpnr-ecp5", DEVICE, "--package", PACKAGE, "--json",
             str(json_out), "--lpf-allow-unconstrained", "--freq", "300"],
            cwd=ROOT, stdout=f, stderr=subprocess.STDOUT)
    out = log.read_text()
    fm = re.findall(r"Max frequency for clock '[^']*':\s*([\d.]+)\s*MHz", out)
    fmax = float(fm[-1]) if fm else None
    return {"module": module, "fmax": fmax, "err": None if fmax else "nextpnr"}


def main():
    mods = sys.argv[1:] or ["speed_iq_pi", "foc_core", "circle_limit_seq"]
    for m in mods:
        r = measure(m)
        f = f"{r['fmax']:.2f} MHz" if r["fmax"] else f"FAIL ({r['err']})"
        print(f"[fmax] {m:22s} {f}")


if __name__ == "__main__":
    main()
